### ISSUE TITLE
dependency ps not listed

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-pac#10]
I am packaging the new snap-pac version and i get:

```
(1/1) Performing snapper post snapshots for the following configurations...
/usr/share/libalpm/scripts/snap-pac: line 27: ps: command not found
==> ERROR: snap-pac should only be called via provided pacman hooks.
```

What is missing here (i think `procps-ng`)? Also are there any other dependencies missing?

**Comment by wesbarnett** [comment]
`ps` is provided by the package `procps-ng`, which is part of the `base` group. Nothing has changed with `ps` being added with the latest release.

**Comment by NicoHood** [comment]
I had a quick chat with the other TUs and it needs to be listed explicit since base is not installed in the devtools chroot build script. Only base-devel is installed. So be careful when building packages. Also never use makepkg, use `extra-x86_64-build` from `devtools`.

**Comment by wesbarnett** [comment]
`sed` should also be added as a requirement then. When I was maintaining this in the AUR it wasn't necessary to list all these since `base-devel` was assued to be installed.

**Comment by NicoHood** [comment]
`base-devel` is assumed to be installed. `base` is not assumed to be installed (at least on build time). I was also wondering why, but it actually makes sense for chroot building. The problem is, that the community does not use chroot building and use makepkg instead. Which is actually a really bad idea in any way. And the build scripts are super simple and dont trash your system with build time dependencies.

Edit: closing this right now. Please check for base deps when building packages. :)
