### ISSUE TITLE
snap-pac should only be called via provided pacman hooks?

### ISSUE THREAD

**Issue by terenzif** [wesbarnett/snap-pac#11]
I am using ApricityOS-gnome, and it seems to me that when installing from graphical program "pamac-manager" the script fails.
After several tests, i made a clean installation of a ApricityOS-gnome, updated, converted to btrfs, installed snapper and set it up, but snap-pac still give the error in subject:
"snap-pac should only be called via provided pacman hooks"
and it doesn't create any snapshot.
So i commented this check and it worked but the snapshot had no comment.

When installing packages from pacman (command line) it works fine

**Comment by wesbarnett** [comment]
Can you show me some pacman logs for both situations (the failure and the one without a comment)? I get the pacman command using `ps` to add as a comment, but it may be that this graphical program calls pacman in another way.

**Comment by wesbarnett** [comment]
I made an update to the `master` branch which I think solves the issue. In addition to giving me some logs, can you test out the script in the `master` branch?

**Comment by wesbarnett** [comment]
Fixed in Release 1.1

**Comment by NicoHood** [comment]
@terenzif the latest snap-pac is now in community. You can test it now.
