### ISSUE TITLE
Add GRUB hook (for grub-btrfs)

### ISSUE THREAD

**Issue by max-baz** [wesbarnett/snap-pac#13]
Hi @wesbarnett,

Initially I came to create a request for supporting `grub-btrfs`, but then I stumbled upon 3f8ea868974818543c14fce65999651b71710cf7 - so it was present at some point, and then was deleted. 

What was the reason for deleting it? I'm new to btrfs, but I'm testing `grub-btrfs` now and it looks like a very interesting feature, it feels that integration with `snap-pac` would be very natural.

UPDATE: I would understand having it disabled by default (not everyone is using `grub-btrfs` after all), but for those who do use it, this is vital that every snapshot created by `snap-pac` is available in the GRUB when it is so needed.

**Comment by wesbarnett** [comment]
I removed it because it really doesn't have to do with snapper or btrfs. If you just want to run `grub-mkconfig` after every pacman transaction (which is what the old files did in this project), just add the following hook to `/usr/share/libalpm/hooks`. Ensure it has the `.hook` file suffix.

```
[Trigger]
Operation = Upgrade
Operation = Install
Operation = Remove
Type = Package
Target = *

[Action]
Description = Generate GRUB configuration file
Depends = grub
When = PostTransaction
Exec = /usr/bin/grub-mkconfig -o /boot/grub/grub.cfg 2> /dev/null
```

**Comment by max-baz** [comment]
Everyone using `snap-pac` and `grub-btrfs` would have to create this exact same hook, that's why I feel it ought to exist in some common place for people to use. Would you agree? 

This repo seemed like a good candidate, alternatively there could be some kind of `snap-pac-grub` package to install just this hook 🤔

**Comment by wesbarnett** [comment]
Sounds liks it could be added to the `grub-btrfs` package.

**Comment by max-baz** [comment]
I disagree because `grub-btrfs` is a project not related to pacman in any way, adding pacman hooks in that repo doesn't make sense to me - just like `snapper` is not related pacman and that's why we have pacman hooks in a separate project called `snap-pac` 🙂

I published the hook as a separate package [aur/snap-pac-grub](https://aur.archlinux.org/packages/snap-pac-grub/), thanks for sharing the code for the hook, it works great 👍
