### ISSUE TITLE
Segfault in snapper on post

### ISSUE THREAD

**Issue by zoqaeski** [wesbarnett/snap-pac#14]
Snapper dumps its core when `snap-pac post` is run. I don't know if this is my configuration, a bug with `snap-pac`, or something else. Here's the output in the journal:

```
Dec 27 13:51:07 tencendor dbus-daemon[406]: [system] Activating service name='org.opensuse.Snapper' requested by ':1.147' (uid=0 pid=24649 comm="snapper --config root create --type pre --cleanup-") (using servicehelper)
Dec 27 13:51:07 tencendor systemd-coredump[24562]: Process 17786 (snapperd) of user 0 dumped core.

    Stack trace of thread 17786:
    #0  0x00007f57f949c860 raise (libc.so.6)
    #1  0x00007f57f949dec9 abort (libc.so.6)
    #2  0x00007f57f9ac5d57 _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6)
    #3  0x00007f57f9ac38c6 _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6)
    #4  0x00007f57f9ac279a __cxa_call_terminate (libstdc++.so.6)
    #5  0x00007f57f9ac3189 __gxx_personality_v0 (libstdc++.so.6)
    #6  0x00007f57f982fca3 _Unwind_RaiseException_Phase2 (libgcc_s.so.1)
    #7  0x00007f57f98304ce _Unwind_Resume (libgcc_s.so.1)
    #8  0x00007f57fa4ba0cc _ZN7snapper14logStreamCloseENS_8LogLevelEPKcjS2_PNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE (libsnapper.so.4)
    #9  0x00007f57fa4885ff _ZN7snapper7SnapperD1Ev (libsnapper.so.4)
    #10 0x0000561cd182593c n/a (snapperd)
    #11 0x0000561cd1825a7c n/a (snapperd)
    #12 0x00007f57f949f448 __run_exit_handlers (libc.so.6)
    #13 0x00007f57f949f49a exit (libc.so.6)
    #14 0x00007f57f9488f51 __libc_start_main (libc.so.6)
    #15 0x0000561cd18093ba n/a (snapperd)
Dec 27 13:51:08 tencendor dbus-daemon[406]: [system] Successfully activated service 'org.opensuse.Snapper'
```
Looking at the output, I suspect that the command for snapper doesn't seem to have the right cleanup option: `snapper --config root create --type pre --cleanup-`, and this triggers the crash. So far I've not needed to actually use my post update snapshots, so I don't know if they've been created correctly.

**Comment by wesbarnett** [comment]
Are you on Arch Linux or another system? What version of snapper, pacman, and bash?

**Comment by zoqaeski** [comment]
Sorry, forgot to include that info. System is Arch Linux, updated roughly weekly. Package versions as of today are:

- pacman is 5.0.2-2
- snapper is 0.5.0-3
- bash is 4.4.012-2

**Comment by wesbarnett** [comment]
I can't seem to reproduce this error. What's the exact command you run when you have this issue?

**Comment by zoqaeski** [comment]
I think I've figured out what causes the error, but I can't reproduce it all the time. Updating or installing non-repository packages with AUR helpers, such as `pacaur` or [`aurutils`](https://github.com/AladW/aurutils) that install built packages one-at-a-time may trigger the segfault in snapper by making the pacman hooks run before the previous snapshot has synced. It may also occur with `makepkg -si`, when building a package requires installing dependencies: the hooks are triggered, but before they sync, `makepkg` starts writing files to the disk, somehow interrupting things.

This is just a hunch from looking at my log files and installing various things.

**Comment by wesbarnett** [comment]
I use aurutils as well and haven't had an issue using `makepkg`. Has this issue come up again? I am going to release v 2.0 soon and wanted to clear this issue.
