### ISSUE TITLE
Make maximum description length configurable

### ISSUE THREAD

**Issue by jonasc** [wesbarnett/snap-pac#15]
Hi,

I figured out that b737252a4ee4f723b946681b3ac2757d793d13fc introduced truncating the description if it was too long. Also #4 kind of goes into that direction.

My problem/point is that I would like the description to be longer.
Is there an easy way to make the maximum description length configurable? Or even optional?

**Comment by wesbarnett** [comment]
There's currently no option to change it without editing the bash script. You can edit the script located at `/usr/share/libalpm/scripts/snap-pac`. The option is called `DESC_LIMIT`.

Any updates to `snap-pac` would cause that change to be overwritten, but I can look into adding an option so that it's easier to configure.

**Comment by jonasc** [comment]
Thanks for the reply. I have seen that I could change the value in the script itself but to be able to survive an update it would be better to have in an additional file.

The easiest way I could imagine is sourcing a configuration file (if it exists) and only setting (some of) the variables when they are not given in the config file.

**Comment by wesbarnett** [comment]
Currently snap-pac sources snapper configuration files (both `/etc/snapper` and the files in `/etc/snapper/configs/`). I'm wondering if the description option should go in those files.

**Comment by max-baz** [comment]
I wouldn't mix the two, truncating description is not really a snapper's configuration, it's purely snap-pac who is doing that...

**Comment by wesbarnett** [comment]
Fixed via #16.
