### ISSUE TITLE
PGP Key import failed

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-pac#2]
Hi,
I currently try to build the AUR package. I know I have to import the key, however gnupg does not find any keyserver. Looking around the internet it seems that you need to add a keyserver to `~/.gnupg/gpg.conf`. On my local system there is this file with a lot of settings + descriptions. In my clean vm there is no such file, but the directory exists and gnupg is installed.

Do you have any idea which package is possibly missing? This keyserver might also be pulled in by thunderbird and the enigmail addon.

Similar Problems:
- https://gpgtools.lighthouseapp.com/projects/66001-macgpg2/tickets/12-create-an-gpgconf-file-of-none-exist

**Comment by wesbarnett** [comment]
What's your exact command in importing the key?

**Comment by NicoHood** [comment]
```
 gpg --recv-keys 0xE4B5E45AA3B8C5C3
```

As it stands in the readme

**Comment by wesbarnett** [comment]
Okay, this sounds like its not an issue with snap-pac or my key in particular, so please file a bug report with GPG or post this on the Arch forums. I'm not going to be able to troubleshoot general GPG issues.

**Comment by NicoHood** [comment]
I've edited my pgp config file now and added a new keysever:

```
keyserver hkp://keys.gnupg.net #old
keyserver hkp://pgp.mit.edu #new
```

See instructions here:
http://jotham-city.com/blog/2015/02/14/verifying-gpg-signatures-for-makepkg/

This also happened on my new system, so you might want to add this information to the FAQ?

**Comment by wesbarnett** [comment]
Great! I'm glad you found the solution. I've put pgp.mit.edu as the keyserver in the instructions now.

**Comment by NicoHood** [comment]
Thanks, thats a super solution. You can also add it to the sticky AUR post.
