### ISSUE TITLE
Implement --no-dbus option to work in chroot environment

### ISSUE THREAD

**Issue by ckotte** [wesbarnett/snap-pac#23]
The snap-pac pre transaction hook fails to execute when executed in a chrooted environment. 

E.g.: One of my other Arch laptops had an issue during installation and I couldn't boot anymore. I needed to boot a rescue system and chroot into the system. However, I couldn't run pacman. The snap-pac pre transaction hook failed because snapper can't reach the DBUS. I needed to add --no-dbus to the snapper command in the snap-pac script to be able to run pacman again.
```
snapper_cmd="snapper --no-dbus --config $CONFIG create --type ..."
```

More information can be found here:
[Snapper is broken due to dependency on dbus](https://github.com/openSUSE/snapper/issues/344)
[Work without DBus](http://snapper.io/2016/12/19/no-dbus-for-all.html)

If you want to use the option only in chroot, you could also implement something like this:
```
if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
  echo "We are chrooted!"
else
  echo "Business as usual"
fi
```
I haven't checked yet if it really works though.

It looks like the DBUS  connection is only there to allow non-root users to use snapper. Since pacman is executed with root permissions, just adding --no-dbus should be sufficient.

**Comment by wesbarnett** [comment]
Please check that this works and solves your issue and return to let me know. Thanks.

**Comment by ckotte** [comment]
What should I check? I already tested the --no-dbus option.

**Comment by wesbarnett** [comment]
Oh, I thought you said you hadn't checked it if works in the chroot.

**Comment by ckotte** [comment]
I tested it in chroot when I fixed the system some while ago. It's still configured and snapshots are created after package installation/update with --no-dbus.

**Comment by wesbarnett** [comment]
Here's what the snapper manpage says about `--no-dbus`:

       --no-dbus
           Operate without a DBus connection.

           Use with caution since a running snapperd will not know about modifications made to the system.

I'm hesitant to just add `--no-dbus` to everything.

**Comment by wesbarnett** [comment]
Adding -`-no-dbus` does allow the snapshot to be taken in chroot, but causes `process ID list syntax error` with the line running `ps`.

**Comment by onelittlehope** [comment]
For my Arch install script, the commands that need to run in a chroot are run using Bash Strict Mode.

i.e.

```
# Bash Strict Mode

set -eECu -o pipefail
IFS=$'\n\t'
```

When snap-pac is installed inside the chroot, via the following command:

```
pacman -S --noconfirm --noprogressbar snap-pac
```

I get an error: `fatal library error, lookup self`

```
[2025-10-19T18:39:05+0100] [PACMAN] Running 'pacman -S --noconfirm --noprogressbar snap-pac'
[2025-10-19T18:39:06+0100] [ALPM] transaction started
[2025-10-19T18:39:06+0100] [ALPM] installed snap-pac (3.0.1-3)
[2025-10-19T18:39:06+0100] [ALPM] transaction completed
[2025-10-19T18:39:06+0100] [ALPM] running '30-systemd-update.hook'...
[2025-10-19T18:39:06+0100] [ALPM] running 'zz-snap-pac-post.hook'...
[2025-10-19T18:39:06+0100] [ALPM-SCRIPTLET] fatal library error, lookup self
[2025-10-19T18:39:06+0100] [ALPM-SCRIPTLET] ==> root: 1
```

<img width="741" height="434" alt="Image" src="https://github.com/user-attachments/assets/ad61758c-25e6-4d00-becc-819075dbb395" />

I didn't get to the bottom of what is causing this. I think its localised to the /usr/share/libalpm/scripts/snap-pac script but I could be wrong.

Anyway, thanks to https://github.com/wesbarnett/snap-pac/pull/18 I am able to bypass the issue by simply running `export SNAP_PAC_SKIP=yes` before the `pacman -S --noconfirm --noprogressbar snap-pac` command.

I'm just documenting this here for future people like me who may run into the issue. 👍
