### ISSUE TITLE
Allow disabling of DESC_LIMIT

### ISSUE THREAD

**Issue by Tank-Missile** [wesbarnett/snap-pac#27]
I want to be able to see all packages listed in the description no matter how many there are to upgrade, but there doesn't appear to be a clean way to do this without setting DESC_LIMIT to a higher number. Perhaps make it so DESC_LIMIT=0 prevents truncation?

**Comment by wesbarnett** [comment]
Okay, I will look into adding this. 

Also, you can always see the packages in `/var/log/pacman.log`.

**Comment by max-baz** [comment]
Setting `DESC_LIMIT=100000` effectively disables the limit, since you'll have to configure `DESC_LIMIT` anyway, honestly there isn't much point in introducing additional conditions in the code itself 😉

**Comment by wesbarnett** [comment]
After thinking about this more, the description is really intended  to just give a quick glance on what happened for that snapshot. You can always look at the pacman log to get all the details if it's not sufficient.
