### ISSUE TITLE
FAQ pacupg

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-pac#3]
Hey, I'd like to know what's the difference between this hook and pacupg. Both are mentioned in the arch wiki page, but nowhere is explained what is the difference or why one is better or not. It would be cool to add this information to the readme. Thanks.
https://aur.archlinux.org/packages/pacupg/

**Comment by wesbarnett** [comment]
I think when you compare the descriptions of both projects you can see the difference. I've tried to highlight that in the current README with the fact with snap-pac you don't have to call another script. pacupg has some additional features which are documented at their upstream.
