### ISSUE TITLE
Provide way to do automated housekeeping?

### ISSUE THREAD

**Issue by etiago** [wesbarnett/snap-pac#31]
Hi Wes,

Thanks for your great work with this!

I'm using snap-pac and I noticed it just carries on creating snapshots for every pacman command that I issue... but as far as I can tell, it doesn't seem to housekeep any of the older snapshots.

Unless my understanding is wrong, if left untouched, it's just a matter of time before the storage gets completely full by snapshots as I keep installing, uninstalling and updating packages.

Do you think it'd be possible to have some form of automated housekeeping built into this package? Or do you have an alternative suggestion for this?

**Comment by wesbarnett** [comment]
Hi Tiago, by default the snapshots are set to cleanup via snapper's cleanup service using the "number" option (when a certain number of snapshots with that setting are reached, the oldest snapshots are removed). Ensure that you have `snapper-cleanup.timer` enabled (with Arch it is set to cleanup daily be default) and that `NUMBER_CLEANUP` is set to `yes` in the snapper configuration. See `man 5 snapper-configs` for more settings related to it.

**Comment by etiago** [comment]
Hi Wes, many thanks for your reply - I was unaware that snap-pac was using the number strategy. Hopefully this will be useful for others in the future :smile: thanks again for this plugin - very useful!

**Comment by wesbarnett** [comment]
Not a problem. 😃 I failed to mention that the user can change the cleanup algorithm used. See ‘man snap-pac’ for how to do that.
