### ISSUE TITLE
How to put a limit on the number of snapshots created by Snap Pac?

### ISSUE THREAD

**Issue by ghost** [wesbarnett/snap-pac#32]
Hi, so I've started using `snapper` instead of timeshift for my BTRFS backup solution. I then found `snap-pac` after this and it works great. However, I can't seem to find a way to set a limit on the number of snapshots to be created like how I can limit the number of hourly, weekly, daily, (etc) snapshots with `snapper` itself. Without a limit, I end up having a lot of snapshots which wastes both disk space and space on the output of `snapper list`. Is there a way to put a limit on these? If not, are there any plans to allow a user to do this?

**Comment by wesbarnett** [comment]
Snapshots created with snap-pac use snapper's number algorithm. So if you have enabled the snapper cleanup service they should be automatically cleaned up.

**Comment by ghost** [comment]
I'll try for a few days with this in mind, thanks a lot!

**Comment by wesbarnett** [comment]
Closing. Feel free to re-open if this is still an issue.
