### ISSUE TITLE
[Q] btrfs-qgroup-rescan is using~100% CPU - how to fix this?

### ISSUE THREAD

**Issue by cmonty14** [wesbarnett/snap-pac#33]
Hi,
first I must say:
snap-pac is wonderful and it works like charm.

However, I'm facing this issue since enabling BTRFS quota:
btrfs-qgroup-rescan is using~100% CPU

Therefore I would like to address this question here although this is **not** related to snap-pac directly:
Can you please advice how to fix this issue?
What would you recommend?

THX

**Comment by wesbarnett** [comment]
I'm sorry that is beyond any advice I an give. I suggest checking the btrfs wiki. They may also have a mailing list.
