### ISSUE TITLE
Unused variables in snap-pac.conf.example?

### ISSUE THREAD

**Issue by GregoryHinton** [wesbarnett/snap-pac#34]
First, thank you for snap-pac; it's a wonderful tool I couldn't live without.

The file extra/snap-pac.conf.example includes the following two lines:
LINK_MODULES="no"
KERNEL_PACKAGE="linux"

But these variables don't appear to be used anywhere. Nor do they seem to be used by snapper. Or am I missing something?

The question arose for me when I created my own /etc/snap-pac.conf file in order to increase DESC_LIMIT from 72 to 132. I also wondered whether I needed to modify KERNEL_PACKAGE since I have both the "linux" and "linux-lts" kernel packages installed on my system.

If you would clarify what's going on here, I'd appreciate it.

**Comment by ckotte** [comment]
This feature was removed two years ago via https://github.com/wesbarnett/snap-pac/commit/1dabe290b6b4b1b11c7fce880647bc9f0ad4efe8. Looks like the maintainer forgot to remove the options from this file.

**Comment by wesbarnett** [comment]
Totally missed this. Thank you. Fixed in #35.
