### ISSUE TITLE
Every time I go back to the pre snapshot, I have to delete /var/lib/pacman/db.lck in order to use pacman

### ISSUE THREAD

**Issue by rankaiyx** [wesbarnett/snap-pac#36]
Every time I go back to the pre snapshot, I have to delete /var/lib/pacman/db.lck in order to use pacman.

OS: Arch Linux
The software you made is very good. It is very useful to me. Thank you very much!

**Comment by NicoHood** [comment]
@rankaiyx I am curios: How do you "go back" to a pre snapshot? Did you write any custom code for this?

**Comment by rankaiyx** [comment]
> @rankaiyx I am curios: How do you "go back" to a pre snapshot? Did you write any custom code for this?
#snapper list
...
50 pre ... 
51 post ...
...
#snapper undochange 50..0

50 and 51 are  created by snap-pac

**Comment by rankaiyx** [comment]
I find this note:
.SS After restoring snapshot from snap-pac, pacman database is locked
The pre/post snaphots are taken while pacman is running, so this is expected.
Follow the instructions pacman gives you (e.g., removing the lock file).

https://github.com/wesbarnett/snap-pac/blob/master/man8/snap-pac.8

I'm sorry. I didn't notice this note before.
Can it be improved to automate this step?

**Comment by rankaiyx** [comment]
I just came up with an idea. Maybe excluding the db.lck file will solve this problem.
I'll try it later.

**Comment by rankaiyx** [comment]
Perfect! The problem has been solved.
#echo /var/lib/pacman/db.lck  >  /etc/snapper/filters/snap-pac_db_lck.txt

Maybe you can include it in the installation script

**Comment by wesbarnett** [comment]
I like it. I'll add a PR for it.

**Comment by wesbarnett** [comment]
@rankaiyx I'm actually curious as well. How are you going back to that snapshot? Typically I use `snapper undochange` which doesn't have an issue with the pacman lock file.

**Comment by wesbarnett** [comment]
@rankaiyx I actually haven't had this problem using `snapper undochange`. In your example, wouldn't it be `snapper undochange 50..51`?

The lock file is actually present in both the pre and post snapshots. So the diff should not include it. The issue of the lock file being present would be if you chose to boot into the pre snapshot for example.

**Comment by wesbarnett** [comment]
Actually adding a filter only prevents the file from being used in a diff, not from being snapshotted.

I'm wondering if this actually should be handled by the snapper package or the pacman package in Arch Linux. `/var/lib/pacman/db.lck` is specific to Arch Linux and holds information on the state of the pacman package. That's exactly what these filters are for.

**Comment by rankaiyx** [comment]
When pacman is about to alter the package database, for example installing a package, it creates a lock file at /var/lib/pacman/db.lck. This prevents another instance of pacman from trying to alter the package database at the same time.
If pacman is interrupted while changing the database, this stale lock file can remain. If you are certain that no instances of pacman are running then delete the lock file.

https://wiki.archlinux.org/index.php/Pacman

I guess here's the step:
1 pacman create /var/lib/pacman/db.lck
2 snap-pac create pre
3 pacman install software
4 snap-pac create post
5 pacman delete /var/lib/pacman/db.lck

I like to use "snapper undochange xx..0"  to bring the current state back to a previous state.
If  don't filter db.lck, it will remain when I go back pre (step 2).
If filter db.lck, snapper will not check it, will not restore the impact of step 5. (Deleted db.lck will not be restored)

**Comment by rankaiyx** [comment]
> @rankaiyx I actually haven't had this problem using `snapper undochange`. In your example, wouldn't it be `snapper undochange 50..51`?
> 
> The lock file is actually present in both the pre and post snapshots. So the diff should not include it. The issue of the lock file being present would be if you chose to boot into the pre snapshot for example.

Considering such a scenario, I might go from 80 to 50.

**Comment by rankaiyx** [comment]
> @rankaiyx I actually haven't had this problem using `snapper undochange`. In your example, wouldn't it be `snapper undochange 50..51`?
> 
> The lock file is actually present in both the pre and post snapshots. So the diff should not include it. The issue of the lock file being present would be if you chose to boot into the pre snapshot for example.

Considering such a scenario, I might go from 80 to 50.

**Comment by rankaiyx** [comment]
> @rankaiyx I actually haven't had this problem using `snapper undochange`. In your example, wouldn't it be `snapper undochange 50..51`?
> 
> The lock file is actually present in both the pre and post snapshots. So the diff should not include it. The issue of the lock file being present would be if you chose to boot into the pre snapshot for example.

Considering such a scenario, I might go from current( 80 ) to 50.

**Comment by wesbarnett** [comment]
What does `snapper undochange` do when the snapshot numbers are reversed? For example, I understand that `snapper  undochange 1..2` reverts all the changes between snapshots 1 and 2. What does `snapper undochange 2..1` do? I can't really find any documentation on it.

**Comment by wesbarnett** [comment]
After thinking about this some more, I do think that since this package is really just a set of pacman hooks and a script, it should not install a file related to snapper or pacman. I have documented in the manpage how to do that if desired. If that file belongs anywhere it is with pacman (if in any package at all). Thanks for the insight on it.
