### ISSUE TITLE
Allow for Snapper Important Label

### ISSUE THREAD

**Issue by jproctor10** [wesbarnett/snap-pac#38]
The cleanup number algorithm has allowed for an important marker for some time https://github.com/openSUSE/snapper/commit/ea4dfd1935a24b29172d04cec1a9360209fb5726. This is done through a userdata variable `important=yes`. 

It would be super useful to be able to add this user variable to specific calls, namely full system updates. Doing that automatically for any `pacman -Syu` would be ideal. But, just introducing an environment variable to modify the snapper command would still enable this functionality.

**Comment by wesbarnett** [comment]
Working on a rewrite of the bash script into Python to make enhancements like these easier to implement.

**Comment by wesbarnett** [comment]
Just to follow up and make this clear, the way to mark userdata `important=yes` for full system upgrades will be to add the following lines to `/etc/snap-pac.ini`:

```ini
[root]
important_commands = ["pacman -Syu"]
```

This is now in the `main` branch and will be in effect in the next release.

**Comment by jproctor10** [comment]
Awesome. Seems simple and configurable with the python rewrite. Thanks
