### ISSUE TITLE
Maximum description length

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-pac#4]
I recently installed my DE on another system and used the following command:

```
pacman -S --needed xorg-server lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings accountsservice light-locker exo garcon gtk-xfce-engine xfce4-panel xfce4-power-manager xfce4-session xfce4-settings xfconf xfdesktop xfwm4 xfce4-terminal compton thunar thunar-volman thunar-archive-plugin thunar-media-tags-plugin catfish mlocate gvfs udisks udisks2 file-roller tumbler ffmpegthumbnailer freetype2 libgsf libopenraw poppler-glib xfce4-mixer gstreamer0.10-good-plugins pulseaudio paprefs pavucontrol alsa-utils gnome-themes-standard gtk-engine-murrine elementary-icon-theme numix-themes networkmanager network-manager-applet dnsmasq plank xfce4-whiskermenu-plugin alacarte nm-connection-editor xfce4-xkb-plugin xfce4-cpugraph-plugin xfce4-cpugraph-plugin xfce4-genmon-plugin xfce4-sensors-plugin dconf-editor xdg-user-dirs xfce4-notifyd
```

This command is also used as snapper description. It totally messes up the list when you call `snapper list`. I do not know what would be the best way to solve this, maybe you can add extended information to the xml file but cut off the description after 100chars or so?

Edit: Another idea would be to fix it upstream. It could by default show a description of 100 chars and a new parameter `--full` shows the full decription.

Edit2: In contrast to that if you run pacman -Syu you have almost no feedback which file were upgraded. It would be nice to add something like `pacman -Syu (nano-3.0-1, linux-4.8-1)` to see which packages were upgraded.

**Comment by wesbarnett** [comment]
I'll look into this. I am surprised snapper doesn't truncate long descriptions.

Concerning "Edit2": I can't easily grab the packages and version info from pacman with the hook. I think the best way for the user to do that is by looking at the snapshot number and finding it in the pacman log (since it is now output by snap-pac it should show up there). The pacman log will then give the exact details of the transaction.

**Comment by wesbarnett** [comment]
So the problem is that I'll never know how big your screen is or anticipate how large your terminal emulator might be. snapper might be able to do that though when it displays via `snapper list`. Can you file an issue with snapper?

**Comment by NicoHood** [comment]
Filed here: https://github.com/openSUSE/snapper/issues/268

You are right, it would be better to fix in snapper, as this way we have more details in the description, if it is really desired. Thatswhy I am closing this and hope to get a fix from upstream.
