### ISSUE TITLE
`Invalid snapshot '--type'.` for all post snapshots (was working before)

### ISSUE THREAD

**Issue by patarapolw** [wesbarnett/snap-pac#49]
**Describe the bug**

Every time I tried to install something with pacman, it says

```
Invalid snapshot '--type'.
==> root: 
```

**To Reproduce**

```sh
pacman -S anything
```

**Expected behavior**

No errors. Create numbered snapshots as always.

**Additional context**

Last entry in Snapper GUI is `python-poetry`

![image](https://user-images.githubusercontent.com/21255931/124600380-d8ddbf00-de90-11eb-8296-2d976f411180.png)

**Comment by wesbarnett** [comment]
Hi, thanks for the report. Can you post a full example of the pacman command you are running, including all arguments?

**Comment by patarapolw** [comment]
Apparently, I deleted that Arch, which I installed with https://github.com/Deebble/arch-btrfs-install-guide

Now, I installed a new Arch with https://github.com/tommytran732/Arch-Setup-Script/blob/main/install.sh which also has `snap-pac`, but it no longer has errors.

**Comment by WhiteHusky** [comment]
I might have an idea why this might occur: `.snapshots` might be world writable. I followed some bad instructions and using `snapper-gui` spit out some warnings regarding this in the terminal when trying to diagnose it. When it was fixed, `snap-pac` started working again.
