### ISSUE TITLE
Missing char in font

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-pac#5]
I recently installed snap-pac for my raspberry pi. However the on screen console does not know this char:

```
    root 10 ✓
```

It is displayed as rectangle. I do not know if there is an equivalent X, but if there is, you would likely also not see it. You should add a dependency to the package or possibly add an alternative to this char?

Edit: over ssh this does not happen

**Comment by wesbarnett** [comment]
Do you know what font you are using where it is missing?

**Comment by NicoHood** [comment]
Uhm I do not know. You can try this at your own arch installation. Just switch via `alt ctrl F2` and upgrade the system. It possibly also just an UTF8 problem, I do not know.

According to this its probably `terminus`:
https://askubuntu.com/questions/97469/what-is-the-default-debian-ubuntu-console-tty-font-called

**Comment by NicoHood** [comment]
Nice solution, thanks.

**Comment by NicoHood** [comment]
I've just noticed that the error still appears on a fresh arch install with xfce installed. It displays the icon as "???". $TERM is set to xterm. This was tested with the raspi again, but this time inside the gui.

**Comment by wesbarnett** [comment]
What font are you using

**Comment by NicoHood** [comment]
Monospace, the default.

The weird thing is, that this only occurs on the raspi (arm) and not on my vm. $LANG differs (C on the raspi, en utf8 on vm) but this does not trigger the bug if i temporary set it to C in the vm. But maybe that is still the reason. `locale charmap` shows the same default output.

If i start `xterm -en C` it shows wrong chars while `xterm -en utf-8` works fine.

**Comment by wesbarnett** [comment]
Sounds like a locale issue. Ensure that you use a UTF-8 locale and its should be fine (Arch Wiki recommends this). Monospace does include the checkmark character.

**Comment by NicoHood** [comment]
It looks to me that the reason is caused by `LANG=C`. You could simply fix this by just checking this variable too. But you are right that utf8 should be used normally.
