### ISSUE TITLE
Auto delete /var/lib/pacman/db.lck from snapshots

### ISSUE THREAD

**Issue by Snogard** [wesbarnett/snap-pac#50]
**Is your feature request related to a problem? Please describe.**
I would like that /var/lib/pacman/db.lck was removed automatically from the create snapshot.
Why? If i use snapper to rollback to a "pre" snapshot, the usage of pacman is locked.

**Describe the solution you'd like**
Maybe we could specify files to be autoremoved from the snapshots through the configuration file

**Comment by wesbarnett** [comment]
I don't think that file should be removed by this package. See discussion at #36
