### ISSUE TITLE
SyntaxError: invalid syntax  Snapper Fails with syntax error in snap-pac

### ISSUE THREAD

**Issue by 6thstring** [wesbarnett/snap-pac#52]
:: Running pre-transaction hooks...
(1/1) Performing snapper pre snapshots for the following configurations...
File "/usr/share/libalpm/scripts/snap-pac", line 40
f"--config {config} create",
^
SyntaxError: invalid syntax
error: command failed to execute correctly
error: failed to commit transaction (failed to run transaction hooks)

**To Reproduce**

**Expected behavior**

**Additional context**
Checking available disk space...                                                                         [1/1]
File "/usr/share/libalpm/scripts/snap-pac", line 41
f"--cleanup-algorithm {cleanup_algorithm}",
^
SyntaxError: invalid syntax
Error: command failed to execute correctly
Error: Failed to commit transaction: failed to run transaction hook

[garuda-inxi-output.txt](https://github.com/wesbarnett/snap-pac/files/8331989/garuda-inxi-output.txt)

**Comment by wesbarnett** [comment]
Looks like you're running an old version of Python? What version? What OS?

**Comment by wesbarnett** [comment]
Stale
