### ISSUE TITLE
How to get `doas` and  `SNAP_PAC_SKIP=y` to work together with `pacman` and `paru`?

### ISSUE THREAD

**Issue by amalgame21** [wesbarnett/snap-pac#54]
`sudo SNAP_PAC_SKIP=y pacman -Syu` works
but
1. command `doas SNAP_PAC_SKIP=y pacman -Syu`
and 
2. command `paru --sudoflags SNAP_PAC_SKIP=y -Syu` with setting `Sudo = doas` in `/etc/paru.conf`

do not work.

Any ways to get `doas` working as `sudo`? Thanks.

**Comment by wesbarnett** [comment]
Need some more details. What does "work" and "does not work" mean here? What is not working?

**Comment by amalgame21** [comment]
Sorry for the misleading statement.
I mean the `SNAP_PAC_SKIP=y` variable can not pass to `doas`, so the snap-pac will not skip with the above commands using `doas`.
I know that it is not the issue of `snap-pac`. I read the manual of `doas` and I cannot find a proper way to pass variables to it. It seems very complicated to me.
I do not know where to seek help for `doas`, so instead I raise a question here.
