### ISSUE TITLE
Rolling back to a presnapshot

### ISSUE THREAD

**Issue by farzawm03** [wesbarnett/snap-pac#55]

**Comment by farzawm03** [comment]
when rolling back to a pre snapshot, it sadly says an already pacman transaction is running, now excluding it manually could be a way, but cant you guys actually do that? or whats the solution? is it okay to remove the lock?

**Comment by wesbarnett** [comment]
https://barnettphd.com/snap-pac/troubleshooting.html

**Comment by farzawm03** [comment]
> https://barnettphd.com/snap-pac/troubleshooting.html

thanks, wasnt sure it wouldnt break anything
