### ISSUE TITLE
Snap-pac errors on line 40 preventing pacman from running

### ISSUE THREAD

**Issue by ZerkerEOD** [wesbarnett/snap-pac#56]
**Describe the bug**
Manjaro snap-pac fails with error on line 40 due to syntax error

**To Reproduce**
1. run anything with pacman
2. errors out

**Expected behavior**
creates the snapshot without error

**Additional context**
I have tried reinstalling to make sure it wasn't a config error I made even though I haven't done anything with snapper configs in a long time. Still didn't work.
![image](https://github.com/wesbarnett/snap-pac/assets/26573385/15a1a187-fc69-4b36-9b27-f8a6e108efd4)

**Comment by wesbarnett** [comment]
What python version do you have installed? That's likely the problem.

**Comment by ZerkerEOD** [comment]
I don't know right now, I am using pyenv but not sure what I have it set to for both python2 or python3. I will check when I turn my computer back on.

**Comment by ZerkerEOD** [comment]
@wesbarnett, that was it, I had Python set to use Python 2.7.18 which was the issue. I changed it to use Python 3.9.16 and it just works again. Thanks!
